version: 2.1
orbs:
  node: circleci/node@3.0.0
jobs:
  test:
    steps:
      - checkout
      - run yarn install
      - run yarn lint
      - run yarn test
  build:
    steps:
      - checkout
      - yarn install
      - yarn build

workflows:
  build-test:
    jobs:
      - test
      - build
