version: 2.1

executors:
  nodejs:
    docker:
      - image: circleci/node:14.10.1

jobs:
  test:
    executor: nodejs
    steps:
      - checkout
      - run: yarn install
      - run: yarn lint
      - run: yarn test

workflows:
  test:
    jobs:
      - test
